/*
  # Fix Identity Column Configuration

  1. Verification
    - Check if ID columns are properly configured as identity columns
    - Ensure they're set to auto-increment correctly
  
  2. Notes
    - Identity columns are already auto-incrementing in PostgreSQL
    - We just need to verify they're configured correctly
*/

-- Verify and ensure identity columns are properly configured for tasks table
DO $$
BEGIN
  -- Check if tasks.id is an identity column, if not make it one
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'tasks' 
    AND column_name = 'id' 
    AND is_identity = 'YES'
  ) THEN
    -- If it's not an identity column, convert it
    ALTER TABLE tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- Verify and ensure identity columns are properly configured for journal_entries table
DO $$
BEGIN
  -- Check if journal_entries.id is an identity column, if not make it one
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'journal_entries' 
    AND column_name = 'id' 
    AND is_identity = 'YES'
  ) THEN
    -- If it's not an identity column, convert it
    ALTER TABLE journal_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- Verify and ensure identity columns are properly configured for flashcard_sets table
DO $$
BEGIN
  -- Check if flashcard_sets.id is an identity column, if not make it one
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'flashcard_sets' 
    AND column_name = 'id' 
    AND is_identity = 'YES'
  ) THEN
    -- If it's not an identity column, convert it
    ALTER TABLE flashcard_sets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- Verify and ensure identity columns are properly configured for flashcards table
DO $$
BEGIN
  -- Check if flashcards.id is an identity column, if not make it one
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'flashcards' 
    AND column_name = 'id' 
    AND is_identity = 'YES'
  ) THEN
    -- If it's not an identity column, convert it
    ALTER TABLE flashcards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- Ensure all tables have the correct NOT NULL constraint on id
ALTER TABLE tasks ALTER COLUMN id SET NOT NULL;
ALTER TABLE journal_entries ALTER COLUMN id SET NOT NULL;
ALTER TABLE flashcard_sets ALTER COLUMN id SET NOT NULL;
ALTER TABLE flashcards ALTER COLUMN id SET NOT NULL;